[package]
name = "blackjack"
version = "0.4.10"
edition = "2021"

[dependencies]
bincode = "1.3.3"
figlet-rs = "0.1.5"
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
whoami = "1.5.2"
